# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_specprepper_wrappers", use_symbols = TRUE, package_name = "specprepper")

#' @docType package
#' @usage NULL
#' @useDynLib specprepper, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

